language: android
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - build-tools-28.0.3
  - android-29
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-29
  - sys-img-armeabi-v7a-android-29
before_install:
- openssl aes-256-cbc -K $encrypted_218f556ebcde_key -iv $encrypted_218f556ebcde_iv
  -in upload-keystore.jks.enc -out upload-keystore.jks -d
